import Header from "@/components/Header/Header";
import "./globals.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BottomHeader from "@/components/Header/BottomHeader";
import Footer from "@/components/Footer/Footer";
import { ReduxProvider } from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-gray-300`}>
                <ReduxProvider>
                    <Header />
                    <BottomHeader />
                    {children}

                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
}
